/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as CandidatoIndexRouteImport } from './routes/candidato.index'
import { Route as CandidatoChatRouteImport } from './routes/candidato.chat'
import { Route as CandidatoTransparenciaRouteImport } from './routes/candidato.transparencia'
import { Route as CandidatoVagasRouteImport } from './routes/candidato.vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoIndexRoute = CandidatoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoChatRoute = CandidatoChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoTransparenciaRoute = CandidatoTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoVagasRoute = CandidatoVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => CandidatoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/candidato/chat': typeof CandidatoChatRoute
  '/candidato/transparencia': typeof CandidatoTransparenciaRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/candidato/': typeof CandidatoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/candidato/chat': typeof CandidatoChatRoute
  '/candidato/transparencia': typeof CandidatoTransparenciaRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/candidato': typeof CandidatoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/candidato/chat': typeof CandidatoChatRoute
  '/candidato/transparencia': typeof CandidatoTransparenciaRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/candidato/': typeof CandidatoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidato'
    | '/configuracoes'
    | '/empresa'
    | '/login'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/candidato/chat'
    | '/candidato/transparencia'
    | '/candidato/vagas'
    | '/candidato/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/empresa'
    | '/login'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/candidato/chat'
    | '/candidato/transparencia'
    | '/candidato/vagas'
    | '/candidato'
  id:
    | '__root__'
    | '/'
    | '/candidato'
    | '/configuracoes'
    | '/empresa'
    | '/login'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/candidato/chat'
    | '/candidato/transparencia'
    | '/candidato/vagas'
    | '/candidato/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatoRoute: typeof CandidatoRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmpresaRoute: typeof EmpresaRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/': {
      id: '/candidato/'
      path: '/'
      fullPath: '/candidato/'
      preLoaderRoute: typeof CandidatoIndexRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/chat': {
      id: '/candidato/chat'
      path: '/chat'
      fullPath: '/candidato/chat'
      preLoaderRoute: typeof CandidatoChatRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/transparencia': {
      id: '/candidato/transparencia'
      path: '/transparencia'
      fullPath: '/candidato/transparencia'
      preLoaderRoute: typeof CandidatoTransparenciaRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/vagas': {
      id: '/candidato/vagas'
      path: '/vagas'
      fullPath: '/candidato/vagas'
      preLoaderRoute: typeof CandidatoVagasRouteImport
      parentRoute: typeof CandidatoRoute
    }
  }
}

interface CandidatoRouteChildren {
  CandidatoChatRoute: typeof CandidatoChatRoute
  CandidatoTransparenciaRoute: typeof CandidatoTransparenciaRoute
  CandidatoVagasRoute: typeof CandidatoVagasRoute
  CandidatoIndexRoute: typeof CandidatoIndexRoute
}

const CandidatoRouteChildren: CandidatoRouteChildren = {
  CandidatoChatRoute: CandidatoChatRoute,
  CandidatoTransparenciaRoute: CandidatoTransparenciaRoute,
  CandidatoVagasRoute: CandidatoVagasRoute,
  CandidatoIndexRoute: CandidatoIndexRoute,
}

const CandidatoRouteWithChildren = CandidatoRoute._addFileChildren(
  CandidatoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatoRoute: CandidatoRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmpresaRoute: EmpresaRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
